
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
debug: true

security:
  basic:
    enabled: true
  user:
    name: user
    password: admin
