server:
  port: 8010
spring:
  application:
    name: ms-consumer-movie-feign
eureka:
  client:
    serviceUrl:
      #defaultZone: http://user:admin@localhost:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true